name:                glados
version:             0.1.0
github:              "EdenComp/GLaDOS"
license:             MIT
author:              "Florian Lauch, Reza Rahemtola, Pablo Levy, Tom Bariteau-Peter, Dorian Moy"
maintainer:          "dreamberd4@gmail.com"
copyright:           "2023 DreamBerd 4"
description:         DreamBerd 4

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  glados:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados

tests:
  testGlados:
    main:                Spec.hs
    source-dirs:         test
    other-modules:       Parse
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados
    - HUnit
